{% set name = "google-cloud-automl" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16547b8e98ff34a26018b8d3bdf1abfd8bac2a2f85438dddca177a1a14e3344d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - proto-plus >=1.15.0,<2.0.0dev
    - protobuf >=3.19.0,<4.0.0dev

test:
  imports:
    - grpc
    - google.cloud.automl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-automl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud AutoML API client library
  description: "Google Cloud AutoML API is a suite of machine learning products that enables developers with limited machine learning expertise to train high-quality models specific to their business needs, by leveraging Google’s state-of-the-art transfer learning, and Neural Architecture Search technology.\nSee the [quick\
    \ start guide](https://googleapis.dev/python/automl/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/automl/latest/index.html
  dev_url: https://github.com/googleapis/python-automl

extra:
  recipe-maintainers:
    - parthea
    - xylar
