{% set name = "google-cloud-automl" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f08abe78d37fb94a3748aa43e66dae2bad52f991cc7740501a341bc6f6387fd5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - google-api-core-grpc >=1.14.0,<2.0.0dev

test:
  imports:
    - grpc
    - google.cloud.automl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-automl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Google Cloud AutoML API client library'
  description: Google Cloud AutoML API is a suite of machine learning products that enables developers with
    limited machine learning expertise to train high-quality models specific to their business needs, by
    leveraging Google’s state-of-the-art transfer learning, and Neural Architecture Search technology.

    See the [quick start guide](https://googleapis.dev/python/automl/latest/index.html#quick-start).

  doc_url: https://googleapis.dev/python/automl/latest/index.html
  dev_url: https://github.com/googleapis/python-automl

extra:
  recipe-maintainers:
    - parthea
    - xylar
